import { GoogleGenAI } from "@google/genai";

// Define styles here to avoid complex relative import issues in serverless environment
const STYLE_PROMPTS: Record<string, string> = {
  "None": "",
  "Photorealistic": ", highly detailed, photorealistic, 8k resolution, raw photography, sharp focus",
  "Cinematic": ", cinematic lighting, movie scene, dramatic atmosphere, color graded, wide angle, 4k",
  "Anime": ", anime style, studio ghibli inspired, vibrant colors, cel shaded, detailed background",
  "Cyberpunk": ", cyberpunk, neon lights, futuristic, high contrast, sci-fi atmosphere, chromatic aberration",
  "Oil Painting": ", oil painting texture, visible brushstrokes, classic art style, rich colors",
  "3D Render": ", 3D render, unreal engine 5, octane render, ray tracing, physically based rendering",
  "Minimalist": ", minimalist, flat design, vector art, simple shapes, clean lines, pastel colors"
};

export default async function handler(request: Request) {
  // CORS Headers for Vercel
  const headers = {
    'Access-Control-Allow-Credentials': 'true',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET,OPTIONS,PATCH,DELETE,POST,PUT',
    'Access-Control-Allow-Headers': 'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version',
    'Content-Type': 'application/json'
  };

  if (request.method === 'OPTIONS') {
    return new Response(null, { status: 200, headers });
  }

  if (request.method !== 'POST') {
    return new Response(JSON.stringify({ message: 'Method not allowed' }), { status: 405, headers });
  }

  try {
    const { prompt, aspectRatio, style } = await request.json();

    if (!process.env.API_KEY) {
      return new Response(JSON.stringify({ message: 'Server configuration error: API_KEY is missing' }), { status: 500, headers });
    }

    if (!prompt) {
      return new Response(JSON.stringify({ message: 'Prompt is required' }), { status: 400, headers });
    }

    // Initialize Gemini API (Running on Server)
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    // Enhance prompt
    const styleSuffix = STYLE_PROMPTS[style] || "";
    const finalPrompt = `${prompt}${styleSuffix}`;

    console.log(`[Server] Generating: ${finalPrompt.substring(0, 50)}...`);

    // Call Model
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [{ text: finalPrompt }]
      },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio || "1:1",
        }
      }
    });

    // Extract Image
    let imageUrl: string | null = null;
    let textMessage: string = "";

    if (response.candidates && response.candidates.length > 0) {
      const parts = response.candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData) {
          imageUrl = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        } else if (part.text) {
          textMessage += part.text;
        }
      }
    }

    if (!imageUrl) {
      return new Response(JSON.stringify({ message: 'No image generated by the model.' }), { status: 500, headers });
    }

    return new Response(JSON.stringify({ imageUrl, textMessage }), { status: 200, headers });

  } catch (error: any) {
    console.error("Backend Error:", error);
    return new Response(JSON.stringify({ message: error.message || 'Internal Server Error' }), { status: 500, headers });
  }
}